In [77]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [2]:
df = pd.read_csv('~/Downloads/mytable_customer_details - Ref_CustDetails.csv')
pd.set_option('max_columns', None)
pd.crosstab(df['contract_type.1'], df.churn, margins=True)

churn              No   Yes   All
contract_type.1
1 Year           1307   166  1473
2 Year           1647    48  1695
Month-to-Month   2220  1655  3875
All              5174  1869  7043

In [3]:
m2m = df[df["contract_type.1"] == "Month-to-Month"]

In [116]:
df

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure_months,is_female,has_churned,has_phone,has_internet,has_phone_and_internet,partner_dependents,start_date,avg_montly_charge,monthly_rate_validation,contract_type.1,phone_service.1,internet_service.1,tenure_month_ages,Phone,Internet,Services
0,0002-ORFBO,Female,No,Yes,Yes,1,1,1,Mailed check,$65.60,$593.30,No,9.04,True,False,True,True,True,3,2020-10-24,$65.60,TRUE,1 Year,One Line,DSL,9,False,False,Phone and Internet
1,0003-MKNFE,Male,No,No,No,2,1,0,Mailed check,$59.90,$542.40,No,9.06,False,False,True,True,True,0,2020-10-24,$59.90,TRUE,Month-to-Month,Two or More Lines,DSL,9,False,False,Phone and Internet
2,0004-TLHLJ,Male,No,No,No,1,2,0,Electronic check,$73.90,$280.85,Yes,3.80,False,True,True,True,True,0,2021-04-02,$73.90,TRUE,Month-to-Month,One Line,Fiber Optic,4,False,False,Phone and Internet
3,0011-IGKFF,Male,Yes,Yes,No,1,2,0,Electronic check,$98.00,"$1,237.85",Yes,12.63,False,True,True,True,True,1,2020-07-07,$98.00,TRUE,Month-to-Month,One Line,Fiber Optic,13,False,False,Phone and Internet
4,0013-EXCHZ,Female,Yes,Yes,No,1,2,0,Mailed check,$83.90,$267.40,Yes,3.19,True,True,True,True,True,1,2021-04-21,$83.90,TRUE,Month-to-Month,One Line,Fiber Optic,3,False,False,Phone and Internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,No,No,No,1,1,1,Mailed check,$55.15,$742.90,No,13.47,True,False,True,True,True,0,2020-06-12,$55.15,TRUE,1 Year,One Line,DSL,13,False,False,Phone and Internet
7039,9992-RRAMN,Male,No,Yes,No,2,2,0,Electronic check,$85.10,"$1,873.70",Yes,22.02,False,True,True,True,True,1,2019-09-26,$85.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,22,False,False,Phone and Internet
7040,9992-UJOEL,Male,No,No,No,1,1,0,Mailed check,$50.30,$92.75,No,1.84,False,False,True,True,True,0,2021-05-31,$50.30,TRUE,Month-to-Month,One Line,DSL,2,False,False,Phone and Internet
7041,9993-LHIEB,Male,No,Yes,Yes,1,1,2,Mailed check,$67.85,"$4,627.65",No,68.20,False,False,True,True,True,3,2015-11-21,$67.85,TRUE,2 Year,One Line,DSL,68,False,False,Phone and Internet
7042,9995-HOTOH,Male,No,Yes,Yes,0,1,2,Electronic check,$59.00,"$3,707.60",No,62.84,False,False,False,True,False,3,2016-05-02,$59.00,TRUE,2 Year,No Phone Service,DSL,63,False,True,Internet

In [4]:
m2m.to_csv("MonthToMonth.csv")
m2m.groupby('churn').Services.agg('count')

churn
No     2220
Yes    1655
Name: Services, dtype: int64

In [5]:
pd.crosstab(m2m.churn, m2m.Services, margins=True)

Services  Internet  Phone  Phone and Internet   All
churn
No             223    425                1572  2220
Yes            153     99                1403  1655
All            376    524                2975  3875

In [117]:
z = m2m[m2m.Services == "Phone and Internet"]

In [121]:
z.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2975 entries, 1 to 7040
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              2975 non-null   object
 1   gender                   2975 non-null   object
 2   is_senior_citizen        2975 non-null   object
 3   partner                  2975 non-null   object
 4   dependents               2975 non-null   object
 5   phone_service            2975 non-null   int64
 6   internet_service         2975 non-null   int64
 7   contract_type            2975 non-null   int64
 8   payment_type             2975 non-null   object
 9   monthly_charges          2975 non-null   object
 10  total_charges            2975 non-null   object
 11  churn                    2975 non-null   object
 12  tenure_months            2975 non-null   float64
 13  is_female                2975 non-null   bool
 14  has_churned              2975 non-null   bool
 15  has_phone                2975 non-null   bool
 16  has_internet             2975 non-null   bool
 17  has_phone_and_internet   2975 non-null   bool
 18  partner_dependents       2975 non-null   int64
 19  start_date               2975 non-null   object
 20  avg_montly_charge        2975 non-null   object
 21  monthly_rate_validation  2975 non-null   object
 22  contract_type.1          2975 non-null   object
 23  phone_service.1          2975 non-null   object
 24  internet_service.1       2975 non-null   object
 25  tenure_month_ages        2975 non-null   int64
 26  Phone                    2975 non-null   bool
 27  Internet                 2975 non-null   bool
 28  Services                 2975 non-null   object
dtypes: bool(7), float64(1), int64(5), object(16)
memory usage: 554.9+ KB

In [12]:
x = z[z.churn == "Yes"]
y = m2m[m2m.Services == "Phone and Internet"]
y = y[y.churn == "No"]

In [18]:
x["monthly_charges"] = x["monthly_charges"].str.strip("$").astype(float)
y["monthly_charges"] = y["monthly_charges"].str.strip("$").astype(float)

In [19]:
x.monthly_charges.mean()

80.73513898788298

In [20]:
x

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure_months,is_female,has_churned,has_phone,has_internet,has_phone_and_internet,partner_dependents,start_date,avg_montly_charge,monthly_rate_validation,contract_type.1,phone_service.1,internet_service.1,tenure_month_ages,Phone,Internet,Services
2,0004-TLHLJ,Male,No,No,No,1,2,0,Electronic check,73.90,$280.85,Yes,3.80,False,True,True,True,True,0,2021-04-02,$73.90,TRUE,Month-to-Month,One Line,Fiber Optic,4,False,False,Phone and Internet
3,0011-IGKFF,Male,Yes,Yes,No,1,2,0,Electronic check,98.00,"$1,237.85",Yes,12.63,False,True,True,True,True,1,2020-07-07,$98.00,TRUE,Month-to-Month,One Line,Fiber Optic,13,False,False,Phone and Internet
4,0013-EXCHZ,Female,Yes,Yes,No,1,2,0,Mailed check,83.90,$267.40,Yes,3.19,True,True,True,True,True,1,2021-04-21,$83.90,TRUE,Month-to-Month,One Line,Fiber Optic,3,False,False,Phone and Internet
21,0023-XUOPT,Female,No,Yes,No,2,2,0,Electronic check,94.10,"$1,215.60",Yes,12.92,True,True,True,True,True,1,2020-06-29,$94.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,13,False,False,Phone and Internet
40,0067-DKWBL,Male,Yes,No,No,1,1,0,Electronic check,49.25,$91.10,Yes,1.85,False,True,True,True,True,0,2021-05-31,$49.25,TRUE,Month-to-Month,One Line,DSL,2,False,False,Phone and Internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7013,9948-YPTDG,Male,No,Yes,No,1,2,0,Electronic check,79.45,"$3,013.05",Yes,37.92,False,True,True,True,True,1,2018-05-30,$79.45,TRUE,Month-to-Month,One Line,Fiber Optic,38,False,False,Phone and Internet
7020,9961-JBNMK,Male,Yes,No,No,1,2,0,Bank transfer (automatic),96.80,"$2,030.30",Yes,20.97,False,True,True,True,True,0,2019-10-28,$96.80,TRUE,Month-to-Month,One Line,Fiber Optic,21,False,False,Phone and Internet
7023,9965-YOKZB,Male,Yes,No,No,2,2,0,Electronic check,83.85,$790.15,Yes,9.42,False,True,True,True,True,0,2020-10-13,$83.85,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,9,False,False,Phone and Internet
7036,9985-MWVIX,Female,No,No,No,1,2,0,Mailed check,70.15,$70.15,Yes,1.00,True,True,True,True,True,0,2021-06-26,$70.15,TRUE,Month-to-Month,One Line,Fiber Optic,1,False,False,Phone and Internet
7039,9992-RRAMN,Male,No,Yes,No,2,2,0,Electronic check,85.10,"$1,873.70",Yes,22.02,False,True,True,True,True,1,2019-09-26,$85.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,22,False,False,Phone and Internet

In [21]:
y.monthly_charges.mean()

76.0073155216286

In [24]:
x.tenure_month_ages.median()

9.0

In [29]:
x["adjusted_yearly_charges"] = x.monthly_charges * 11

In [105]:
y["adjusted_yearly_charges"] = y.monthly_charges * 11

In [32]:
x["yearly_charges"] = x.monthly_charges * 12

In [106]:
y["yearly_charges"] = y.monthly_charges * 12

In [33]:
x

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure_months,is_female,has_churned,has_phone,has_internet,has_phone_and_internet,partner_dependents,start_date,avg_montly_charge,monthly_rate_validation,contract_type.1,phone_service.1,internet_service.1,tenure_month_ages,Phone,Internet,Services,yearly_charges,adjusted_yearly_charges
2,0004-TLHLJ,Male,No,No,No,1,2,0,Electronic check,73.90,$280.85,Yes,3.80,False,True,True,True,True,0,2021-04-02,$73.90,TRUE,Month-to-Month,One Line,Fiber Optic,4,False,False,Phone and Internet,886.8,812.90
3,0011-IGKFF,Male,Yes,Yes,No,1,2,0,Electronic check,98.00,"$1,237.85",Yes,12.63,False,True,True,True,True,1,2020-07-07,$98.00,TRUE,Month-to-Month,One Line,Fiber Optic,13,False,False,Phone and Internet,1176.0,1078.00
4,0013-EXCHZ,Female,Yes,Yes,No,1,2,0,Mailed check,83.90,$267.40,Yes,3.19,True,True,True,True,True,1,2021-04-21,$83.90,TRUE,Month-to-Month,One Line,Fiber Optic,3,False,False,Phone and Internet,1006.8,922.90
21,0023-XUOPT,Female,No,Yes,No,2,2,0,Electronic check,94.10,"$1,215.60",Yes,12.92,True,True,True,True,True,1,2020-06-29,$94.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,13,False,False,Phone and Internet,1129.2,1035.10
40,0067-DKWBL,Male,Yes,No,No,1,1,0,Electronic check,49.25,$91.10,Yes,1.85,False,True,True,True,True,0,2021-05-31,$49.25,TRUE,Month-to-Month,One Line,DSL,2,False,False,Phone and Internet,591.0,541.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7013,9948-YPTDG,Male,No,Yes,No,1,2,0,Electronic check,79.45,"$3,013.05",Yes,37.92,False,True,True,True,True,1,2018-05-30,$79.45,TRUE,Month-to-Month,One Line,Fiber Optic,38,False,False,Phone and Internet,953.4,873.95
7020,9961-JBNMK,Male,Yes,No,No,1,2,0,Bank transfer (automatic),96.80,"$2,030.30",Yes,20.97,False,True,True,True,True,0,2019-10-28,$96.80,TRUE,Month-to-Month,One Line,Fiber Optic,21,False,False,Phone and Internet,1161.6,1064.80
7023,9965-YOKZB,Male,Yes,No,No,2,2,0,Electronic check,83.85,$790.15,Yes,9.42,False,True,True,True,True,0,2020-10-13,$83.85,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,9,False,False,Phone and Internet,1006.2,922.35
7036,9985-MWVIX,Female,No,No,No,1,2,0,Mailed check,70.15,$70.15,Yes,1.00,True,True,True,True,True,0,2021-06-26,$70.15,TRUE,Month-to-Month,One Line,Fiber Optic,1,False,False,Phone and Internet,841.8,771.65
7039,9992-RRAMN,Male,No,Yes,No,2,2,0,Electronic check,85.10,"$1,873.70",Yes,22.02,False,True,True,True,True,1,2019-09-26,$85.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,22,False,False,Phone and Internet,1021.2,936.10

In [34]:
m2m

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure_months,is_female,has_churned,has_phone,has_internet,has_phone_and_internet,partner_dependents,start_date,avg_montly_charge,monthly_rate_validation,contract_type.1,phone_service.1,internet_service.1,tenure_month_ages,Phone,Internet,Services
1,0003-MKNFE,Male,No,No,No,2,1,0,Mailed check,$59.90,$542.40,No,9.06,False,False,True,True,True,0,2020-10-24,$59.90,TRUE,Month-to-Month,Two or More Lines,DSL,9,False,False,Phone and Internet
2,0004-TLHLJ,Male,No,No,No,1,2,0,Electronic check,$73.90,$280.85,Yes,3.80,False,True,True,True,True,0,2021-04-02,$73.90,TRUE,Month-to-Month,One Line,Fiber Optic,4,False,False,Phone and Internet
3,0011-IGKFF,Male,Yes,Yes,No,1,2,0,Electronic check,$98.00,"$1,237.85",Yes,12.63,False,True,True,True,True,1,2020-07-07,$98.00,TRUE,Month-to-Month,One Line,Fiber Optic,13,False,False,Phone and Internet
4,0013-EXCHZ,Female,Yes,Yes,No,1,2,0,Mailed check,$83.90,$267.40,Yes,3.19,True,True,True,True,True,1,2021-04-21,$83.90,TRUE,Month-to-Month,One Line,Fiber Optic,3,False,False,Phone and Internet
5,0013-MHZWF,Female,No,No,Yes,1,1,0,Credit card (automatic),$69.40,$571.45,No,8.23,True,False,True,True,True,2,2020-11-18,$69.40,TRUE,Month-to-Month,One Line,DSL,8,False,False,Phone and Internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7033,9975-SKRNR,Male,No,No,No,1,0,0,Mailed check,$18.90,$18.90,No,1.00,False,False,True,False,False,0,2021-06-26,$18.90,TRUE,Month-to-Month,One Line,No Internet Service,1,True,False,Phone
7036,9985-MWVIX,Female,No,No,No,1,2,0,Mailed check,$70.15,$70.15,Yes,1.00,True,True,True,True,True,0,2021-06-26,$70.15,TRUE,Month-to-Month,One Line,Fiber Optic,1,False,False,Phone and Internet
7037,9986-BONCE,Female,No,No,No,1,0,0,Bank transfer (automatic),$20.95,$85.50,Yes,4.08,True,True,True,False,False,0,2021-03-24,$20.95,TRUE,Month-to-Month,One Line,No Internet Service,4,True,False,Phone
7039,9992-RRAMN,Male,No,Yes,No,2,2,0,Electronic check,$85.10,"$1,873.70",Yes,22.02,False,True,True,True,True,1,2019-09-26,$85.10,TRUE,Month-to-Month,Two or More Lines,Fiber Optic,22,False,False,Phone and Internet
7040,9992-UJOEL,Male,No,No,No,1,1,0,Mailed check,$50.30,$92.75,No,1.84,False,False,True,True,True,0,2021-05-31,$50.30,TRUE,Month-to-Month,One Line,DSL,2,False,False,Phone and Internet

In [61]:
z = x[['churn', 'yearly_charges', 'adjusted_yearly_charges']]

In [99]:
x.pivot_table(index=tenure_month_ages, yearly_adjusted_charges)

SyntaxError: positional argument follows keyword argument (<ipython-input-99-b73b30e6511a>, line 1)

In [101]:
x.yearly_charges.meadian()

AttributeError: 'Series' object has no attribute 'meadian'

In [103]:
x.adjusted_yearly_charges.mean()

888.0865288667142

In [107]:
y.yearly_charges.mean()

912.0877862595421

In [113]:
y.yearly_charges.mean()

912.0877862595421

In [114]:
x.yearly_charges.mean()

968.8216678545963

In [115]:
y.shape

(1572, 31)